config/routes.rb
Rails.application.routes.draw do
  resources :flats

  root to: 'flats#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true, length: { minimum: 5, maximum: 50 }
  validates :description, presence: true, length: { maximum: 200 }
  validates :address, presence: true
  validates :price_per_night, presence: true, inclusion: { in: (10..99) }
  validates :number_of_guests, presence: true, inclusion: { in: (1..20) }
  validates :image, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  # GET /flats
  # GET /flats.json
  def index
    @flats = Flat.all
  end

  # GET /flats/1
  # GET /flats/1.json
  def show
  end

  # GET /flats/new
  def new
    @flat = Flat.new
  end

  # GET /flats/1/edit
  def edit
  end

  # POST /flats
  # POST /flats.json
  def create
    @flat = Flat.new(flat_params)

    respond_to do |format|
      if @flat.save
        format.html { redirect_to @flat, notice: 'Flat was successfully created.' }
        format.json { render :show, status: :created, location: @flat }
      else
        format.html { render :new }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flats/1
  # PATCH/PUT /flats/1.json
  def update
    respond_to do |format|
      if @flat.update(flat_params)
        format.html { redirect_to @flat, notice: 'Flat was successfully updated.' }
        format.json { render :show, status: :ok, location: @flat }
      else
        format.html { render :edit }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flats/1
  # DELETE /flats/1.json
  def destroy
    @flat.destroy
    respond_to do |format|
      format.html { redirect_to flats_url, notice: 'Flat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flat
      @flat = Flat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flat_params
      params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= form_with(model: @flat, local: true) do |form| %>
  <% if @flat.errors.any? %>
    <div id="error_explanation">
      <h4 style="color: red;"><%= pluralize(@flat.errors.count, "error") %> prohibited this flat from being saved:</h4>

      <ul style="list-style: none;">
      <% @flat.errors.full_messages.each do |message| %>
        <li style="margin-left: 0;"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">

    <%= form.text_field :name, id: :flat_name, placeholder: "Name your flat!" %>
  </div>

  <div class="field">

    <%= form.text_field :address, id: :flat_address, placeholder: "What's the address?" %>
  </div>

  <div class="field">

    <%= form.text_area :description, id: :flat_description, placeholder: "Tell us about your place!" %>
  </div>

  <div class="field">

    <%= form.number_field :price_per_night, id: :flat_price_per_night, placeholder: "How much is the rent?" %>
  </div>

  <div class="field">

    <%= form.number_field :number_of_guests, id: :flat_number_of_guests, placeholder: "How many people does it fit?" %>
  </div>

  <div class="field">

    <%= form.text_field :image, id: :flat_image, placeholder: "Link an image of your flat!" %>
  </div>
  <br>

  <div class="actions">
    <%= form.submit "Create!", :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/flats/edit.html.erb
<h1>Editing Flat</h1>

<%= render 'form', flat: @flat %>

<%= link_to 'Show', @flat %> |
<%= link_to 'Back', flats_path %>

app/views/flats/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <h1>Flats</h1>
  </div>
  <div class="row">
    <div class="col col-xs-12 col-sm-6 col-sm-offset-3">
      <%= link_to 'New Flat', new_flat_path, class: "btn btn-primary" %>
    </div>
    <% @flats.each do |flat| %>
      <div class="col col-xs-12 col-sm-6 card">
        <%= image_tag(flat.image, class: "image") %>
        <%= link_to "GO TO FLAT", flat, class: "cta" %>
        <!-- <div class="cta">GO TO FLAT</div> -->
        <div class="details">
          <div class="name"><%= flat.name %></div>
          <div class="address"><%= flat.address %></div>
          <div class="descr"><%= flat.description %></div>
        </div>
        <div class="numbers">
          <div class="price">
            <i class="fas fa-euro-sign"></i>
            <div class="price"><%= flat.price_per_night %></div>
          </div>
          <div class="capacity">
            <div class="capacity"><%= flat.number_of_guests %></div>
            <i class="fas fa-bed"></i>
          </div>
        </div>
        <div class="controls">
          <%= link_to 'Show', flat %><%= link_to 'Edit', edit_flat_path(flat) %><%= link_to 'Destroy', flat, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="formgrid">
  <h1>New Flat</h1>
  <div class="row">
    <div class="col col-xs-12 col-md-6 col-md-offset-3">
      <%= render 'form', flat: @flat %>

    </div>

  </div>
  <br>
  <%= link_to 'Back', flats_path %>
</div>

app/views/flats/show.html.erb
<p id="notice"><%= notice %></p>
<div class="singlebox">
  <%= image_tag(@flat.image, class: "theimage") %>
    <!-- </div> -->
  <div class="thedetails">
    <!-- <div class="col col-xs-12 col-sm-6 details"> -->
    <div>
      <!-- <strong>Name:</strong> -->
      <div><i class="fas fa-home" style="font-size: 30px; margin-bottom: 14px;"></i></div>
      <%= @flat.name %>
    </div>

    <div>
      <!-- <strong>Address:</strong> -->
      <div><i class="fas fa-map-marker-alt" style="font-size: 30px; margin-bottom: 14px;"></i></div>
      <%= @flat.address %>
    </div>

    <div>
      <!-- <strong>Description:</strong> -->
      <div><i class="fas fa-pencil-alt" style="font-size: 30px; margin-bottom: 14px;"></i></div>
      <%= @flat.description %>
    </div>
  </div>
  <div class="thefigures">
    <!-- <div class="col col-md-3 col-md-offset-3 figures"> -->
      <div class="theprices">
        <div><i class="far fa-money-bill-alt" style="font-size: 40px;"></i></div>
        <strong>Price per night:</strong>
        <%= @flat.price_per_night %>
      </div>

      <div class="theguests">
        <div><i class="fas fa-users" style="font-size: 40px;"></i></div>
        <strong>Number of guests:</strong>
        <%= @flat.number_of_guests %>
      </div>
    <!-- </div> -->
    <!-- <div class="col col-md-3 col-md-offset-6 booking"> -->
      <div class="thebooking">
        <h3>Book Now</h3>
        <input type="date" placeholder="start date">
        <input type="date" placeholder="end date">
      </div>
    <!-- </div> -->
  </div>
  <%= link_to 'Edit', edit_flat_path(@flat) %> |
  <%= link_to 'Back', flats_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbMvp</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>